servers:
  - name: worker-kubes25
    user: kub
    hosts: [10.0.0.135]
    port: 22
    # password: $CCN_PASSWORD
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: forwareder-forum
  #   user: isanchez
  #   hosts: [10.11.0.31]
  #   port: 22
  #   password: qnZ!6or3Wq9F
    #  pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: manager-1
  #   user: kub
  #   hosts: [10.60.0.53]
  #   port: 22
  #   password: changeme01
  # - name: manager-2
  #   user: kub
  #   hosts: [10.60.0.54]
  #   port: 22
  #   password: changeme01
  # - name: forum-worker-2
  #   user: kub
  #   hosts: [10.60.0.12]
  #   port: 22
  #   password: changeme01
  #   # pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: forum-worker-3
  #   user: kub
  #   hosts: [10.60.0.13]
  #   port: 22
  #   # password: changeme01
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: forum-master-1
  #   user: kub
  #   hosts: [10.60.0.1]
  #   port: 22
  #   # password: changeme01
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: ccn-forwarder
  #   user: root
  #   hosts: [10.40.0.91]
  #   port: 22
  #   password: $CCN_PASSWORD
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: cbi
  #   user: kub
  #   hosts: [10.11.1.113]
  #   port: 22
  #   password: $CCN_PASSWORD
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: devops
  #   user: kub
  #   hosts: [10.10.0.117, 10.10.0.118, 10.10.0.119]
  #   port: 22
    # password: $CCN_PASSWORD
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: devops-dns
  #   user: kub
  #   hosts: [10.10.0.54]
  #   port: 22
    # password: $CCN_PASSWORD
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: worker-kubes-news
  #   user: kub
  #   hosts: [10.0.0.222, 10.0.0.223]
  #   port: 22
    # password: changeme01
    # pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: test
  #   user: kub
  #   hosts: [10.10.0.3]
  #   port: 22
  #   # password: ""
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: altel
  #   user: kub 
  #   hosts: [172.31.41.48]
  #   port: 22
  #   # password: $AltelPass
  #   pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  #   # pkey: "/home/dml/.ssh/altel.pem"
  # - name: proxmox-staging
  #   user: root
  #   hosts: [10.0.0.94, 10.0.0.104]
  #   port: 22
  #   password: MLtBkRNB5M6vWuAV
    # pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  # - name: dia-brasil
  #   user: dml
  #   hosts: [10.106.68.194]
  #   port: 22
  #   password: $PASS_DIA_BRASIL
    # pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
