servers:
  - name: masters
    user: kub
    hosts: [10.0.0.41, 10.0.0.42, 10.0.0.43]
    port: 22
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: master-01
    user: kub
    hosts: [10.0.0.41]
    port: 22
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: managers
    user: kub
    hosts: [10.0.0.69, 10.0.0.67]
    port: 22
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: manager-01
    user: kub
    hosts: [10.0.0.69]
    port: 22
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: manager-02
    user: kub
    hosts: [10.0.0.67]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: workers
    user: kub
    hosts: [10.0.0.44, 10.0.0.45, 10.0.0.46, 10.0.0.47, 10.0.0.48, 10.0.0.49]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: worker-01
    user: kub
    hosts: [10.0.0.44]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: worker-02
    user: kub
    hosts: [10.0.0.45]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: worker-03
    user: kub
    hosts: [10.0.0.46]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: worker-04
    user: kub
    hosts: [10.0.0.47]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: worker-07
    user: kub
    hosts: [10.0.0.51]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"
  - name: golden-image
    user: kub
    hosts: [10.0.0.6]
    port: 22
    # password: changeme01
    pkey: "/home/dml/.ssh/id_rsa_kubernetes-unelink"